app = 'roomly-n8n'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  N8N_PROTOCOL = "https"
  N8N_TRUST_PROXY = "true"
  N8N_SECURE_COOKIE = "false"
  NODE_ENV = "production"
  EXECUTIONS_TIMEOUT = "300"
  EXECUTIONS_TIMEOUT_MAX = "600"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
